name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  milliseconds:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # output will be available to future steps
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
